.TH FUZZ 1

.SH NAME
fuzz  \- kernel fuzzer from Plan 9 space

.SH SYNOPSIS
.B fuzz
[
.B -s
.I seed
]
[
.B -n
.I rounds
]
.B call …

.SH DESCRIPTION
.I Fuzz

.PP
The options are:
.PD

.TP
.B -s \fIseed
Use a specific \fIseed\fR for number generation.

.TP
.B -n \fIrounds
Perform fuzzing for \fIrounds\fR iterations.

.PP
.SH EXAMPLES

To print all system calls known by fuzz:
.EX
fuzz ?
.EE

To fuzz the read and write system calls for two rounds:
.EX
fuzz -n 2 read write
.EE

To fuzz the close system call for 5 rounds using a particular seed:
.EX
fuzz -s '-750199259' -n 5 close
.EE

.PP
.SH SOURCE
.B https://bitbucket.org/cpre43121/fuzz-c

.PP
.SH "SEE ALSO"
.IR intro (2),
.IR syscall (1)

.PP
.SH BUGS

Oh yeah.

